### ISSUE TITLE
Filter by Author Search not working correctly 

### ISSUE THREAD

**Issue by netuserxda** [wstyres/Zebra#1034]
**Describe the bug**

If you go in filter by Author and Search “Mostafa” It shows some other authors but not this one
![E8E15425-37A1-4489-8011-F59DBF38266A](https://user-images.githubusercontent.com/7758573/78355228-5d011280-757b-11ea-8143-fcdfe988a61a.png)

![F833EE1A-98B7-4728-AB02-E7A3D319B24E](https://user-images.githubusercontent.com/7758573/78355303-7ace7780-757b-11ea-8a65-4e70b5a57e59.png)

**To Reproduce**

Go in Settings Filter and search by Author Mostafa

**Expected behavior**

It should show and allow to filter:
Mostafa
m_r19891989@yahoo.com

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version : 13.3
 - Zebra Version : 1.1 beta4
 - Device Type : iPhone XS
 - Jailbreak Type : unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
This is because he didn't write his email address in control file. Zebra is filtering by email address so cannot handle in this case.

**Comment by netuserxda** [comment]
> This is because he didn't write his email address in control file. Zebra is filtering by email address so cannot handle in this case.

But I do see email address under developer’s name, or you are talking about somewhere else ?  

Will zebra be able to filter without email, otherwise spamer just need to not input email and filter become useless

**Comment by eve0415** [comment]
> But I do see email address under developer’s name, or you are talking about somewhere else ?

Yeah, I'm talking about the file in package (deb) file.

> Will zebra be able to filter without email, otherwise spammer just need to not input email and filter become useless

I hope @wstyres has an idea for this.

**Comment by PoomSmart** [comment]
The search logic only took the author record with both name and email defined, I committed changes that will make it takes when either field is present. One drawback is those records cannot be checked.

`cell.accessoryType = authorDetail[1].length && [[selectedAuthors allKeys] containsObject:authorDetail[1]] ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryNone;`

Suggestions?

**Comment by PoomSmart** [comment]
Maybe we should be able to fill in the missing email address to be the unique identifier based on the name. For example, `musfata_unspecified1df5xe245@email.com` for the author name `musfata`.

**Comment by wstyres** [comment]
What I've done is kept the author storing mechanism as it is so that authors are stored based on their email and there is a secondary value that is marked as the author name that was originally selected.

Originally, authors without emails were not displayed which is why they did not show up in search. I've added the ability to select author names individually by duplicating their information in case they are missing one field (name: name or email: email). Searching and blocking by email is still the primary and most effective way of blocking authors like this since they are **supposed** to be using emails so that their purchasers can contact them in case there is a problem (but that is another story). But you can now block authors based on their name again I case there is the odd author that does not add an email.

This will need some additional testing in the next beta to make sure that it works ok.

**Comment by wstyres** [comment]
Example: 
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-11 at 15 13 18](https://user-images.githubusercontent.com/19736790/79052801-fb8a1500-7c06-11ea-956d-0f32884f650b.png)
