### ISSUE TITLE
Jumpy/Laggy animation when pulling down on the empty search menu

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1044]
**Describe the bug**
It’s another very small one, but if you look a bit closely you can see how the search header will kind of “eat itself” with how quickly and choppy it pulls the header to the smaller centered text

**To Reproduce**
Go to the search page, and pull up on the menu to go down and watch the header bar. Compare with how it looks in comparison to the home and changes tabs animations

**Expected behavior**
To have a smoother animation when pulling up to go down, like in the changes or home page

**Screenshots**
Video of it in action: https://youtu.be/--eX_NAkIOw

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.3**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1~beta 4**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**
n/a

**Comment by wstyres** [comment]
I notice nothing wrong with the search header. Are you referring to the fact that it doesn't allow you to keep the title in a minimized state? This is because there are no cells on the search page and you can't scroll that far down to keep it minimized. Regardless, this is a minor annoyance and this is iOS behavior with and there's not much we can do about it.
