### ISSUE TITLE
Cannot install package because it depends on firmware(>11.2)

### ISSUE THREAD

**Issue by p0358** [wstyres/Zebra#1061]
**Describe the bug**

**To Reproduce**
1. Add this repo (just an example package for this): https://amaha831.github.io/repo/
2. Open package `speakershare` and hit the install button
3. Open queue
4. You see error and this info after tapping on `i` button: https://i.imgur.com/1iken92.png

**Expected behavior**
There would be no error and I could install the package normally.
Please note that it installed without any issues with Cydia.

**Screenshots**
![](https://i.imgur.com/1iken92.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.1~beta4
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 0.9.8.2 beta

**Crash Log or System Log**
It doesn't crash, so I don't have a crash log.

**Additional context**

**Comment by p0358** [comment]
Also here's the link to mentioned package's source code: https://github.com/amaha831/speakershare
which doesn't seem to explicitly state firmware>11.2 dependency itself anywhere

**Comment by eve0415** [comment]
Can’t reproduce for me.
![6BCBFF6C-8882-4E73-B94E-8339ED06E5F0](https://user-images.githubusercontent.com/40632436/79000520-bb378200-7b87-11ea-8449-2eccf182c4f9.png)

However, if I am right developer should write `firmware (>>11.2)` not (>11.2)

**Comment by p0358** [comment]
@eve0415 I think it might be because the package maintainer could had already removed the requirement for the time being, as I reported this issue to them as well
![image](https://user-images.githubusercontent.com/5182588/79000923-d5546e80-7b4d-11ea-8564-3c5e0c97ea84.png)

**Comment by eve0415** [comment]
https://github.com/wstyres/Zebra/issues/938#issuecomment-596087023

It’s not a zebra’s bug.

**Comment by p0358** [comment]
@eve0415 That's a very fair point there. However we should still keep in mind it worked in Cydia, which leads to inconsistent behavior here. More packages could be affected, where people unaware of the issue push the package (because they tested in Cydia and it didn't complain). And then users could blame Zebra in the first place for throwing and error where Cydia doesn't. And from the linked issue, it appears this isn't the first time.
Probably mitigation in Zebra would save some headaches, but I'm not sure if that's the right decision to make. And I have no idea why Cydia accepts the non-standard format in the first place either...

**Comment by p0358** [comment]
Ah, I see
```
[2] The relations < and > were previously allowed, but they were confusingly defined to mean earlier/later or equal rather than strictly earlier/later. dpkg still supports them with a warning, but they are no longer allowed by Debian Policy.
```

**Comment by wstyres** [comment]
So it seems that you've already figured things out, my comment [here](https://github.com/wstyres/Zebra/issues/938#issuecomment-596087023) explains things pretty well and you did find that comment about the legacy behavior. 

Cydia might have been made at a time where the `<` and `>` signs were still allowed in Debian policy but because most packages aren't going to include that behavior and it is no longer allowed in policy since Zebra was created, we're not going to allow it in dependency resolution so that we don't "reinforce bad behavior" (not that it is *bad* behavior but in order to keep things more in line with what they are supposed to be).

The simple (and quicker) solution here is for the package maintainer to change the Depends line  to >> so that it can be resolved now instead of when the next Zebra update would come out.
