### ISSUE TITLE
BigBoss dark mode is broken

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1074]
BigBoss’ dark mode is broken. Downgraded Zebra to test if this was a Zebra issue or a BigBoss issue. It’s a Zebra issue.

Don’t know when it broke but it is working properly in Zebra 1.0.7. Now it shows white on black instead of being correctly colored.

**Screenshots**

![B1E99C75-6E74-498B-BE31-69A5F5F72FC1](https://user-images.githubusercontent.com/51668635/79157935-c08a0c00-7dd5-11ea-8660-1a3c01608233.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 5
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: uncover
System dark mode and system accent color.

**Comment by wstyres** [comment]
BigBoss' dark mode isn't "broken", I've just updated the way Zebra posts its dark mode information in 1.1 and BigBoss has not updated to support it. I contacted 0ptimo awhile back when dealing with some rogue ads that would appear on Zebra and asked him about updating it. He said he'd be glad to do so when 1.1 was out of beta so that was the plan for updating it.

**Comment by worldlydev** [comment]
Ok gotcha. Close the issue if you want to.
