### ISSUE TITLE
Issues Clear Web Cache

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#1131]
After using “Clear Web Cache” in Zebra, I try to open Safari in settings app and it crashes. Also now safari always refreshes after reopening.

1. Open Zebra
2. Open Settings
3. Choose clear web cache
4. Close Zebra
5. Open Settings app
6. Choose Safari

I expect to be able to open the Safari settings.

 - iOS 12.4
 - Zebra 1.1-beta6
 - iPhone 6s
 - unc0ver 3.4.1

[Cr4shed Log](https://pastebin.com/k8RNsGxr) 

**Additional Context**
Persists after jailbreaking with tweaks off and Restore RootFS.

**Comment by wstyres** [comment]
Are you sure that it is Zebra causing this issue? It is unlikely for something like this to persist after a RootFS restore. I just tried to do it on iOS 13 and could not reproduce, I will see if I can reproduce in an iOS 12 simulator or on an iOS 12 device.

**Comment by rctfan929** [comment]
Pretty sure was able to access before. Do you suggest anything else I could try to fix?

**Comment by wstyres** [comment]
Not really sure, the error is strange and the crash log doesn't point to one particular problem.

**Comment by wstyres** [comment]
Just checked myself on a device running iOS 12.4, 
1. Opened the Safari section in the settings app to confirm I could access it before reseting Zebra's web cache
2. Opened Zebra, reset web cache.
3. Quit settings
4. Opened settings app again and opened Safari section without crash.

So it looks like this issue is unrelated to Zebra and unfortunately I cannot fix it.
