### ISSUE TITLE
Package removed from repo causes source to become local source

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1176]
**Describe the bug**

Okapi was removed from Packix by the developer. Now the source for Okapi, which I already have installed on my device is local source. Even though it was installed through Packix.

**To Reproduce**

^

**Expected behavior**

It should still display as Packix.

**Screenshots**

![D546B29F-9E77-41CD-8E6C-A73036C3DA19](https://user-images.githubusercontent.com/51668635/80799346-ed486c80-8ba6-11ea-8f1c-737b3df0ad36.jpeg)
![AC28F19D-A1FD-444F-A34C-1EB6D294977C](https://user-images.githubusercontent.com/51668635/80799348-efaac680-8ba6-11ea-80a6-ad4f0a1d32ca.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 8
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
This is intended behavior. If it is no longer available from Packix I see no reason why it should be labeled as "from Packix". The file is no longer hosted so you can't reinstall it from anywhere. If the same version of the package were to be hosted on another repo Zebra would then link the package to that repo so that you could install it from there instead.
