### ISSUE TITLE
Zebra won’t refresh sources

### ISSUE THREAD

**Issue by lopeZmario504** [wstyres/Zebra#1252]
**Describe the bug**
Sources will not refresh. I can download packages that are already there but if there’s an update I can not see them because the sources won’t refresh

**To Reproduce**
Steps to reproduce the behavior: refresh sources

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.3>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.4>
 - Device Type [e.g. iPhone or iPad]: <iPhone >
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
This is likely a problem with a source you have added being down or inaccessible. There was a bug where Zebra would take 4 1/2 minutes before failing a source but we've fixed this in 1.1.6 it should now cap out at 25 seconds before failing a source and displaying an error message.

Please try out 1.1.6 and let us know if the issue is resolved.

**Comment by lopeZmario504** [comment]
The issue is fixed in the new version
