### ISSUE TITLE
Have an option to use the cydia url scheme

### ISSUE THREAD

**Issue by SarKaa** [wstyres/Zebra#1259]
**Is your feature request related to a problem? Please describe.**
Before an update, you zebra would "hijack" cydia's url schemes, which was useful, but some people had problems with that
**Describe the solution you'd like**
Me, and other people, found that to be useful, but we had to use an external tweak to get it back, so all i'm saying is can you just add an option to select which url schemes you would want to use

**Comment by wstyres** [comment]
The Cydia URL scheme was removed completely because it was too confusing for a lot of users who complained about the inability to open Cydia URLs in Cydia.

The "selecting which URL schemes" approach is a horrible UX design. If you download an update to Zebra, Cydia, or any other application that hooks the Cydia scheme, you have to re-do the url scheme selection within Zebra due to a way that iOS works. That is why an external tweak is a much better approach since it never requires re-setting the schemes.

Until a lot less people decide to use Cydia, iOS scheme management improves by allowing which scheme to use for which app or, there is a new discovery made about how iOS handles URL schemes, we're not going to add the Cydia URL scheme back into Zebra.
