### ISSUE TITLE
VOIP Calls & Online Game Connection Issues When Refreshing Sources

### ISSUE THREAD

**Issue by andmpel** [wstyres/Zebra#1514]
**Describe the bug**
When on Webex calls, Microsoft Teams calls, Discord calls, online games, it seems that when I refresh my sources while on a cal or in game, on another device the call (video/audio/game) freezes for 10-30 seconds until it reconnects. 

Not sure what causes this. Sometimes my VPN can even drop off, can kick other devices off the network. Is it because of the amount of requests Zebra is pushing at once maybe?

**To Reproduce**
Open VOIP software and get on a call on a device
My device is a work device using Cisco Anyconnect VPN to tunnel to my work
My personal Windows desktop is on a wired connection and I game on that. Online games freeze or get choppy
On personal jailbroken iPhone, open zebra and refresh sources
The call will immediately hang for a period of time, often resuming within 10-30 seconds

**Expected behavior**
Refreshing sources should not disrupt other devices or applications connections.

**Screenshots**
N/A

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2\~beta2b
 - Device Type [e.g. iPhone or iPad]: iPhone 5s
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Seems irrespective of VOIP software uses. Also I'm not certain but it can cause buffering while streaming. Or if refreshing sources while playing online games my connection will lag. 
I use a PiHole (Network level ad blocker/DNS Server) on a raspberry pi 3 as a recursive DNS server. Don't know if that could be a choke point if it's creating too many DNS queries at once? But I doubt that.

**Comment by wstyres** [comment]
Haven't heard this before other than possibly https://github.com/wstyres/Zebra/issues/1488 (but that issue seems to be more on-device related), looks like an odd sequence of events and might be very difficult to track down. 

You're saying refreshing Zebra is affecting other network devices? It is a little hard to believe that one device could be causing that much network traffic. iOS generally limits the amount of outgoing requests so having one iPhone take up your entire bandwidth seems unlikely unless there is a network configuration issue.

I just got in a Discord call and did a full reset of Zebra to refresh sources and noticed no interruptions or reduction in call quality. I am running PiHole as well for DNS is I don't think the issue is there. Are there any other details that might help us track this issue down?

**Comment by andmpel** [comment]
I accidentally broke my jailbreak trying to upgrade some packages or what not. I RestoreRootFS'd it and installed the latest Zebra beta. No more issue. Not sure if it was the restore or the updated Zebra beta. But it's not a problem for me anymore.
