### ISSUE TITLE
Missing Packages

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#183]
**Describe the bug**
Some packages appear in Cydia but not in Zebra.

**To Reproduce**
1. Open both Cydia & Zebra
2. Search for a package
    (I searhed for BetterCCXI Weather Add-On)

**Expected behavior**
I expext the package to appear.

**Screenshots**
![C1213DB0-5A0D-47CC-AE5C-46F2ED6DC69B](https://user-images.githubusercontent.com/46878212/59561265-438eda00-8fec-11e9-810c-e06473967255.png)
![93548B23-05DB-4964-9FEE-CAA1F763E3E6](https://user-images.githubusercontent.com/46878212/59561266-438eda00-8fec-11e9-8338-e55352d585db.png)

**Device Information (please complete the following information):**
 - iOS 12.1.2
 - beta14
 - iPhone 6s

**Comment by PoomSmart** [comment]
This is because, on Zebra, not all packages are loaded at once. If you scroll down, it will load more packages. The reason that Zebra doesn't load all packages at once is due to memory management issue. Cydia can handle this, and this is because its sophisticated `libapt` and friends. Zebra does simpler things and that comes with trade-offs.

A possible compensation would be having "Load More" button at top-right.
