### ISSUE TITLE
Some repos don't load

### ISSUE THREAD

**Issue by mastercreeper66** [wstyres/Zebra#27]
Some repos don't load and give 404 error:
https://xninja.xyz/apt/
http://kindadev.com/apt/
https://shade-zepheri.github.io/
http://smokin1337.github.io/

![9F899B6F-B9DC-4DC8-8EFC-FBF4BBC9CB83](https://user-images.githubusercontent.com/31628599/56853675-5dd10380-692b-11e9-92b3-3433e94c36ce.png)
![ABEE20E2-A2B5-4AF3-8D39-85999DCCCFCA](https://user-images.githubusercontent.com/31628599/56853676-5dd10380-692b-11e9-942c-5f4ef2e416b3.png)

 - iOS 12.1.1 beta 1
 - Zebra 1.0~beta5
 - iPhone 6s plus

**Comment by wstyres** [comment]
Most of these repos probably use Packages.gz rather than Packages.bz2. I'll fix that in the next beta.

**Comment by rubrdcky** [comment]
I was going to submit a similar issue but I'll just comment here. Would it be possible to also show which repo isn't loading? I have the same problem but can't figure out from the error messages which repo is the problem.

**Comment by wstyres** [comment]
I'll change the error messages to show the repo URL. The spinning indicators on the sidebar should also give an indication of which repo isn't loading.

**Comment by wstyres** [comment]
Repos that only provide Packages.gz are supported as of 3281a93, as of ccf658f repo URLs are shown for download errors, and as of a943c5f repos that are made using Windows (Packages files have Windows line endings) are supported. 

I've tested all of the repos you provided and the only one that still doesn't work is http://smokin1337.github.io/ due to the fact that it doesn't support https:// and that it has an improper filename for its Packages.gz.
