### ISSUE TITLE
There’s one feature missing that is preventing from making Zebra my primary manager

### ISSUE THREAD

**Issue by mason1171** [wstyres/Zebra#290]
If possible, can a feature be introduced where debs aren't deleted after installation? It can be toggled by a switch. Im essentially asking for the non piracy part of Cydown.
![166385AF-7E57-481D-A43A-A064302CB776](https://user-images.githubusercontent.com/33766621/62101454-7242d600-b263-11e9-96ec-fe29fac03e19.png)

**Comment by TheRealKeto** [comment]
This sounds great, but it will come with one issue, making Zebra a target for piracy. With this feature implemented, users will be able to locally download packages, meaning that users can also download paid packages, 

A good alternative would be to cache free tweaks and exclude paid ones, but even if paid tweaks are excluded, people may reconsider Zebra as more of "piracy tool"  rather than a package manager.

**Comment by mason1171** [comment]
> This sounds great, but it will come with one issue, making Zebra a target for piracy. With this feature implemented, users will be able to locally download packages, meaning that users can also download paid packages,
> 
> A good alternative would be to cache free tweaks and exclude paid ones, but even if paid tweaks are excluded, people may reconsider Zebra as more of "piracy tool" rather than a package manager.

Your alternative seems foolproof to me as the app already caches downloaded debs but they are just deleted upon installation. I dont see how this would be considered piracy if the tweaks are free and available to the public

**Comment by Samgisaninja** [comment]
get debKeeper12 from www.tateu.net/repo

**Comment by mason1171** [comment]
Oh shit. I didnt know DebKeeper is still being updated. Thanks, Samg.

**Comment by PoomSmart** [comment]
Any concerns toward piracy will not be considered.
