### ISSUE TITLE
Native depictions

### ISSUE THREAD

**Issue by neumaif02** [wstyres/Zebra#305]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use the same native depiction solution that Installer

**Describe alternatives you've considered**
Use Sileo native depiction solutions

**Comment by wstyres** [comment]
Because of the loss in ad revenue for repos that is created as a result of "native depictions" and due to the limitation in control over how your package is displayed, we feel that it is not the best course of action at this time to include these in Zebra. These could possibly be included in the future but for now I'm closing the issue.
