### ISSUE TITLE
User setting to choose Reddit app

### ISSUE THREAD

**Issue by edmechem** [wstyres/Zebra#364]
Tapping a Story at top of Changes tab always opens Apollo.

I'd prefer these opened in the official Reddit app.

There should be a user setting to choose which installed Reddit app will handle these stories (and any other reddit links). (falling back to mobile Safari if none are installed). I suppose it should also allow user to choose 'web view' if they want to view these inside Zebra.

**Comment by wstyres** [comment]
This is a bit of a complicated issue to implement. The main thinking behind opening Apollo first is that usually if someone has Apollo installed they'd prefer to use that over the official reddit app (otherwise, why even have Apollo installed at all?) and if the reddit app is installed without Apollo, open it in that app instead. If neither are installed then we can just open it in safari.

UI-wise this isn't very easy to solve, it complicates a lot of settings for a feature that Zebra isn't really meant to provide (after all, it is a package manager and not a reddit client).

**Comment by edmechem** [comment]
Hm.  Fair enough.  How about providing the ability to long-press, to copy the URL?  That would allow the user to workaround this?

**Comment by worldlydev** [comment]
> Hm. Fair enough. How about providing the ability to long-press, to copy the URL? That would allow the user to workaround this?

Lol. That's already possible.
![EC0EA9BB-32BA-48CB-B3F2-4DA9F1330E08](https://user-images.githubusercontent.com/51668635/65158015-f169b480-da31-11e9-9567-cddb74fb62e4.png)

**Comment by edmechem** [comment]
Actually, when I long press on an article, nothing happens - and when I force touch it, Zebra erroneously shows me the "peek" view for *the first item* in the Changes list - not a menu with options for the article:
