### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by ThaPandaKingg** [wstyres/Zebra#388]
Recently Zebra has been draining my batter bad, even when i’m not using it. I checked if it was any of my tweaks, but couldn’t find anything. 

i’m running zebra 1.0~beta22-1 on iphone xs max 12.4
![40D2E62C-EF3F-43DC-9C55-347CB8A95EC4](https://user-images.githubusercontent.com/48893291/66880683-945a1380-ef89-11e9-8050-96a928c5480a.png)

**Comment by wstyres** [comment]
Are you by chance running the latest unc0ver beta?

**Comment by ThaPandaKingg** [comment]
yes i am

**Comment by ThaPandaKingg** [comment]
> Are you by chance running the latest unc0ver beta?

yes i am

**Comment by wstyres** [comment]
This appears to be an issue with the latest unc0ver beta where sbreload is taking up a lot of memory while respringing. The reason Zebra is blamed for this is because it calls the `sbreload` command when respringing after installing a package. There is an issue on the unc0ver GitHub about it and hopefully it will be resolved in a future beta of unc0ver. Here is the link for future reference: https://github.com/pwn20wndstuff/Undecimus/issues/1577.
