### ISSUE TITLE
[Localize] Russian Translation

### ISSUE THREAD

**Issue by iGerman00** [wstyres/Zebra#442]
**What language are you adding?**
Russian (ru)

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://anonfile.com/obYfn29bn1/Localizable_strings

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
Yes, since right now ;)
iGerman#1179

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
iGerman

or @iGerman00 (Twitter)

**Comment by wstyres** [comment]
Russian translation support was already added in #430 but you can take a look [here](https://github.com/wstyres/Zebra/blob/master/Zebra/ru.lproj/Localizable.strings) to make sure all of the translations are correct. I will still give you the Discord role since you did translate it and in case we need to you translate more Russian strings in the future.
