### ISSUE TITLE
[Localize]

### ISSUE THREAD

**Issue by joostiphone** [wstyres/Zebra#443]
**What language are you adding?**

Dutch (Netherlands)

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**

https://joostcloud.nl/s/XiaV3pTls7TKGkj

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**

joostiphone

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
Crooked
www.twitter.com/@crookedvult

**Comment by wstyres** [comment]
Dutch translations were already added in #435 you can double check the translations [here](https://github.com/wstyres/Zebra/blob/master/Zebra/nl.lproj/Localizable.strings) and edit them if there are any translations that need to be changed. I couldn't find you on our Discord but if you join our server then I'll give you the translator role so that you can help if more Dutch translations are needed in the future.
