### ISSUE TITLE
[BUG]Crashes when hitting confirm for removing packages 

### ISSUE THREAD

**Issue by DamnRobotAliens** [wstyres/Zebra#501]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version: 12.4 
 - Zebra Version: 1.0~beta24 
 - Device Type: iPhone X

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

After adding any package to the queue and tapping the Confirm button in the queue view Zebra crashes

**To Reproduce**
Steps to reproduce the behavior:

1. Add any package to the queue
2. Open the queue
3. Tap the confirm button

**Expected behavior**
A clear and concise description of what you expected to happen.

Zebra should continue with the actions requested by the user without crashing.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Device Information (please complete the following information):**


* iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
* Zebra Version [e.g. 1.0~beta1 or beta1]: 1.0~beta24
* Device Type [e.g. iPhone or iPad]: iPhone

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

Process: Zebra
Bundle id: xyz.willy.Zebra
Device: iPhone X, iOS 12.4

Exception type: NSInvalidUnarchiveOperationException
Reason: Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)
Culprit: Unknown
Call stack:
0   CoreFoundation                      0x0000000202f9a9a4 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000002021739f8 objc_exception_throw
2   CoreFoundation                      0x0000000202ea4bc0 -[NSCache init]
3   UIFoundation                        0x000000020d639de8 UINibDecoderDecodeObjectForValue
4   UIFoundation                        0x000000020d63a16c UINibDecoderDecodeObjectForValue
5   UIFoundation                        0x000000020d5d9304 -[UINibDecoder decodeObjectForKey:]
6   UIKitCore                           0x000000022fd4ce70 -[UIView initWithCoder:]
7   UIKitCore                           0x000000022fcfb2e8 -[UIScrollView initWithCoder:]
8   UIKitCore                           0x000000022fc04d6c -[UITextView initWithCoder:]
9   UIFoundation                        0x000000020d639f28 UINibDecoderDecodeObjectForValue
10  UIFoundation                        0x000000020d5d9304 -[UINibDecoder decodeObjectForKey:]
11  UIKitCore                           0x000000022f5a0508 -[UIRuntimeConnection initWithCoder:]
12  UIFoundation                        0x000000020d639f28 UINibDecoderDecodeObjectForValue
13  UIFoundation                        0x000000020d63a16c UINibDecoderDecodeObjectForValue
14  UIFoundation                        0x000000020d5d9304 -[UINibDecoder decodeObjectForKey:]
15  UIKitCore                           0x000000022f59ddf0 -[UINib instantiateWithOwner:options:]
16  UIKitCore                           0x000000022f33926c -[UIViewController _loadViewFromNibNamed:bundle:]
17  UIKitCore                           0x000000022f339c14 -[UIViewController loadView]
18  UIKitCore                           0x000000022f339ed8 -[UIViewController loadViewIfRequired]
19  UIKitCore                           0x000000022f33a628 -[UIViewController view]
20  UIKitCore                           0x000000022f297724 -[UINavigationController _startCustomTransition:]
21  UIKitCore                           0x000000022f2ab714 -[UINavigationController _startDeferredTransitionIfNeeded:]
22  UIKitCore                           0x000000022f2acb3c -[UINavigationController __viewWillLayoutSubviews]
23  UIKitCore                           0x000000022f28fd4c -[UILayoutContainerView layoutSubviews]
24  UIKitCore                           0x000000022fd7b170 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
25  QuartzCore                          0x00000002074d7c60 -[CALayer layoutSublayers]
26  QuartzCore                          0x00000002074dcc08 CA::Layer::layout_if_needed(CA::Transaction*)
27  QuartzCore                          0x000000020743f3e4 CA::Context::commit_transaction(CA::Transaction*)
28  QuartzCore                          0x000000020746d620 CA::Transaction::commit()
29  QuartzCore                          0x000000020746e15c CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
30  CoreFoundation                      0x0000000202f2bd08 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
31  CoreFoundation                      0x0000000202f26a30 __CFRunLoopDoObservers
32  CoreFoundation                      0x0000000202f26fac __CFRunLoopRun
33  CoreFoundation                      0x0000000202f267c0 CFRunLoopRunSpecific
34  GraphicsServices                    0x000000020512779c GSEventRunModal
35  UIKitCore                           0x000000022f8e3c38 UIApplicationMain
36  Zebra                               0x00000001004c817c Zebra + 147836
37  libdyld.dylib                       0x00000002029ea8e0 start

**Additional context**
Add any other context about the problem here.

**Comment by wstyres** [comment]
This is an issue with the latest Xcode version. I will push a new beta out as soon as possible.
