### ISSUE TITLE
Add a colour wheel for the tint/app icon colours so users have full control over customisation instead of using preset colours

### ISSUE THREAD

**Issue by DrConflict** [wstyres/Zebra#597]
Please add a colour wheel for the tint colours so users have full control over customisation instead of preset colours. This would make sense for a futuristic package manager like zebra. being able to apply these colours to the app icon would be a cool option as well. The more user customisation, the better right? These are obviously just visual features and not a priority but I hope this can be considered for future updates. Thanks in advance!

**Comment by wstyres** [comment]
We've decided on not implementing a full color picker and instead opting for a [few more accent colors to chose from](https://twitter.com/getzebra/status/1225270304701911040?s=21) in 1.1. We did this so that we can at least have some control over how the app looks and we still want it to look nice with any combination chosen by the user. That isn't to say that a tweak still couldn't be made to accomplish the task of providing a color picker (and it would likely be pretty easy given the code I've added for it).
