### ISSUE TITLE
[Improvement] Jailbreak Incompatibility alert disable

### ISSUE THREAD

**Issue by shortbow123** [wstyres/Zebra#694]
It would be nice to disable the warning I get for have the Cydia repo on Zebra EVERY time I refresh my sources. Just a toggle in settings is all that matters. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment]
The jailbreak incompatibility alert is not something to be ignored (so a setting to disable it will not be added). If you have an incompatible repo in your sources and you install a package from that source the consequences could result in a loss of your jailbreak and having to restore your device. If you believe that the warning appears as an error then that is a bug and should be reported. Otherwise, you should remove the repo from your sources list as Zebra does not actually download any packages from this source if it is incompatible (so the repo is useless).

**Comment by shortbow123** [comment]
>The jailbreak incompatibility alert is not something to be ignored (so a setting to disable it will not be added). If you have an incompatible repo in your sources and you install a package from that source the consequences could result in a loss of your jailbreak and having to restore your device. If you believe that the warning appears as an error then that is a bug and should be reported. Otherwise, you should remove the repo from your sources list as Zebra does not actually download any packages from this source if it is incompatible (so the repo is useless).

@wstyres But it is the Cydia repo, the official one with ALL of the Cydia packages needed for a functional jailbreak.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment]
What jailbreak are you using?

**Comment by shortbow123** [comment]
>What jailbreak are you using?

@wstyres Checkra1n

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eve0415** [comment]
What version are you using then. I mean Zebra

**Comment by shortbow123** [comment]
>What version are you using then. I mean Zebra

@eve0415 Latest release, Zebra Beta 33

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eve0415** [comment]
Any screenshot of that warning?

**Comment by wstyres** [comment]
The utility repo required for checkra1n is https://apt.bingner.com/ **NOT** https://apt.saurik.com/. Bingner's Repo contains all of the packages from Saurik's repo but they are updated for modern jailbreaks (11 and up). Saurik's repo should only be used on jailbreaks lower than 11.0 (NOT on unc0ver, Electra, Chimera, or checkra1n). Any package on Saurik's repo will most likely not work on a modern jailbreak anyway and this is why the Bingner repo was created.
