### ISSUE TITLE
Unable to install a tweak, but Cydia can.

### ISSUE THREAD

**Issue by Wo0of** [wstyres/Zebra#721]
**Describe the bug**
I tried to install Reddit No Ads but was not able to. It worked for cydia however.

**To Reproduce**
Try installing Reddit No Ads

**Expected behavior**
See screenshot link

**Screenshots**
https://imgur.com/a/6iogS7k

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: ios 12.4.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0 rc2
 - Device Type [e.g. iPhone or iPad]: iPhone 6
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:  Checkra1n
 
**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Repo: https://cydia.kemmis.info

**Comment by Wo0of** [comment]
For the expected behaviour Im not expecting an error. I messed up on that one lol

**Comment by wstyres** [comment]
This is a problem with the repo itself and not Zebra. The maintainer of https://cydia.kemmis.info is not following the Debian format for their control fields and is using `FileName` for the location of the file to download instead of the documented `Filename` (the problem here is the capital N in `FileName`) I would suggest contacting the repo maintainer in order for this issue to be fixed.

**Comment by wstyres** [comment]
To clarify, Cydia may be able to install the package because it is more lenient with the specification of these fields but Zebra is a little more strict when it comes to field names.

**Comment by kemmis** [comment]
How about you implement the specs a little more lenient? I'm happy to fix this on my repo, but what about all the other devs that have to create repos and host their tweaks? This was literally work for my repo with zebra a month or two ago, so from my perspective, devs on this project have introduced bugs that should probably be considered instead of ignored (like the comment above)... sorry to be a bit negative here. 

The Cydia dev had a lot more foresight when he implemented his package manager. You might take his lead on this one.

**Comment by kemmis** [comment]
Just an update on my end: I did end up changing a few things on my end, and that did solve the problem: https://github.com/kemmis/cydia.kemmis.info/commit/a2febaed5e4f30fa4a9657354080af5b30a6b46f
