### ISSUE TITLE
Remove Notification Bubble After Updating Packages

### ISSUE THREAD

**Issue by BananaManCJ** [wstyres/Zebra#826]
After updating Zebra, the notification bubble still stays there until I open the app again. It should be cleared before closing the app after an update.

**Comment by wstyres** [comment]
Could you take a screen recording of the issue to show us the problem?

**Comment by eve0415** [comment]
![719456BC-A463-49F2-9C26-11C168493957](https://user-images.githubusercontent.com/40632436/72700607-a69eab80-3b8f-11ea-926a-f786451c2f89.png)
It means like this. It happens when after upgrading tweaks and then respring using “Restart Springboard” button. It doesn’t happen when pressing “Close Zebra” when upgrading zebra and when pressing “Done” button.

**Comment by eve0415** [comment]
And it happens when Zebra automatically closes when updating Zebra.
https://cdn.discordapp.com/attachments/572784833714192395/668686987376590848/video0.mp4

**Comment by BananaManCJ** [comment]
I was talking about what @eve0415 is talking about.

**Comment by wstyres** [comment]
So the only case of this bug is when upgrading Zebra?

**Comment by eve0415** [comment]
and when respringing directly after installing package

**Comment by wstyres** [comment]
In 1.1 this might be happening with all packages as stated in #876

**Comment by BananaManCJ** [comment]
> In 1.1 this might be happening with all packages as stated in #876

Can confirm, I have noticed this in 1.1

**Comment by wstyres** [comment]
Should be fixed as of f1f734aa91cf3e75584d5ff62a60165cc318ad58.
