### ISSUE TITLE
Automatic removal of orphaned packages

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#827]
Right now, when you add a package to removal queue, the package's dependencies will not be added to the queue. This results in orphaned/unused packages.

One solution is to check for package's dependencies when adding to removal queue, and if the package has dependencies that no other package uses, they would be added to the queue.

Other solution is to run `apt autoremove` after every package removal.

For example, package `Slyph` from `repo.daus.ch` has `MDausch Utils` as a dependency. If you do not have `Artsy` from the same source, package `MDausch Utils` will be an orphaned package.

I would like for orphaned packages to automatically be added to the queue when removing its parent package or to run `apt autoremove` after a package uninstallation to automatically remove them.

**Comment by wstyres** [comment]
I think the solution that would actually be applied here would to just have a GUI option to `apt autoremove`. There are a lot of edge cases that apply with dependencies that are no longer required and a user might be confused why a package is being removed when it doesn't actually need to be removed.

For example, if you install an activator add-on (which would require activator to be installed) and then remove that add-on, activator would be removed as well since it was originally installed by that add-on. But Activator can be used perfectly fine by itself without any add-ons and a user may have already configured it to do so.

Another problem would be substrate. The first tweak you install would be installing substrate and safe mode, if thats the only tweak on your system and you uninstall it, substrate would have to be re-downloaded once the user wants another tweak. 

I think the best solution would just be a button (somewhere) to run `apt autoremove`. If the user were to ever want to do that.

**Comment by gkeep** [comment]
Huh. Never looked at it from this perspective. You are right.

Maybe you could add a section in Settings with Respring button (#822), drop tables and this - advanced settings, of sorts.

**Comment by wstyres** [comment]
Yeah that sounds like what will happen for both buttons.

**Comment by wstyres** [comment]
So it looks like the way Zebra installs packages doesn't really support the auto remove feature of apt as we implicitly install these dependencies. For now, this request is not possible but as Zebra improves, we might revisit the idea.
