### ISSUE TITLE
IOS 7 support

### ISSUE THREAD

**Issue by swekley** [wstyres/Zebra#928]
**Describe the solution you'd like**
I'd like to use Zebra on my ipad 3rd gen on ios 7.1.2, as Zebra is actually great at finding packages without knowing the exact name of the package

**Describe alternatives you've considered**
I could update the ipad to ios 9, but that would slow it down so bad I'd rather throw it away than use ios 9.

**Comment by wstyres** [comment]
Unfortunately, iOS 9 is the lowest Zebra can go at the moment because it uses a lot of newer APIs that just don't exist on iOS 7. We try our best to keep the lowest at iOS 9 as much as possible but sometime in the future we may have to remove support for iOS 9 simply due to the lack of overall support and availability of APIs.
