### ISSUE TITLE
Option to disable auto refresh

### ISSUE THREAD

**Issue by minuzc** [wstyres/Zebra#929]
Currently, no package managers have a way to turn off auto refresh which can be a very annoying process which runs almost every time you open the app. I for one, prefer to manually refresh my sources and I think a simple option to disable auto refresh should be added to Zebras settings. Thanks.

**Comment by worldlydev** [comment]
Adding this here because it's related. Would it be possible for Zebra to not refresh archived repos? For example, ModMyi and ZodTTD are huge and never get updates so there is no point in refreshing them.
![1D82F927-5B69-4E7D-9953-BEDDA3012FDA](https://user-images.githubusercontent.com/51668635/75723905-865d2300-5cdd-11ea-827b-783861a731b6.jpeg)

**Comment by wstyres** [comment]
Implemented in d1cfe503.
