### ISSUE TITLE
Infinitely loading sources

### ISSUE THREAD

**Issue by MemesDank456** [wstyres/Zebra#950]
**Describe the bug**
When I refresh sources in zebra, they never finish loading.

**To Reproduce**
1: Reload Sources

**Expected behavior**
Finish reloading sources.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta2-1
 - Device Type [e.g. iPhone or iPad]: iPhone 8
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue. (I dont have any crash logs, nothing crashed so i dont know where to get a log)

**Comment by wstyres** [comment]
Are you sure that one source isn't causing the issue? What does the console say when refreshing the Source Cache in Settings > Advanced?

**Comment by gerbil-snot** [comment]
I’ve got the same issue, the console stays black and does nothing when resetting source cache

**Comment by wstyres** [comment]
Could you post a screen recording? Does deleting Zebra's database resolve the issue?

**Comment by eve0415** [comment]
I don't think it's a same issue but I'll just leave it here because it looks similar.
I haven't had any issue with refreshing entire sources in the source tab, but loading specific source by going into source package selection and swiping down, never seems to finish refreshing or it's just UI bug.
Refreshing a specific source by tapping reload in the source tab (swipe left on any package) seems fine.
https://cdn.discordapp.com/attachments/572784833714192395/691104746441801818/video0.mp4
I did refresh and clearing cache and I'm one the latest beta (1.0~beta2)

**Comment by gerbil-snot** [comment]
I would send a screen record, but it’s working now
