### ISSUE TITLE
Loading bar always at the top

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#979]
**Is your feature request related to a problem? Please describe.**
The description are cut off when it is loading long description.
![IMG_5347](https://user-images.githubusercontent.com/40632436/77597635-d927a480-6f42-11ea-943f-321e8b0ae23a.PNG)
![IMG_5345](https://user-images.githubusercontent.com/40632436/77597637-db89fe80-6f42-11ea-81df-0fb109a0100f.PNG)

**Describe the solution you'd like**
I therefore, would like the loading bar always at the top so I could know it still loading and how long would it take it to finish.

**Comment by wstyres** [comment]
The problem here is that the page is still "loading" but it does not give us a new estimated progress because the page has reported that it is finished (when it really isn't) this is the case when loading Javascript Libraries on the depiction or some ads.

This is more of a bug that the full depiction isn't showing, it might require a lot of work to rewrite this so that everything works properly so we might have to revisit this for 1.2.

**Comment by wstyres** [comment]
In 1.2 depictions aren't shown until they are fully loaded due to page height concerns. This should resolve your issue.
