### ISSUE TITLE
Filtered authors still appears in update

### ISSUE THREAD

**Issue by unclehumble** [wstyres/Zebra#998]
**Describe the bug**
I have filtered some authors that spam the update, and yet they keep appearing once they instill their spam command( fake update)

**To Reproduce**
Add a random author to the filter list, I usually add them to author

**Expected behavior**
Close zebra and reopen. No concrete effect is noticeable as author apps/ themes still appears on update section. Couple of hours, when author initiates a new update, it still all appears.

**Screenshots**
This can be provided if requested

**Device Information (please complete the following information):**
 - iOS Version [e.g. 13.3]: 
 - Zebra Version [e.g latest beta]: 
 - Device Type [e.g. iPhone 11 pro max ]: 
 - Jailbreak Type [e.g. unc0ver,.]: 

**Crash Log or System Log**
N/A

**Comment by worldlydev** [comment]
Same happend to me.
![6309564D-233D-4B71-8E2F-F653E27C0AFE](https://user-images.githubusercontent.com/51668635/77809637-d76bf700-7090-11ea-8107-25b2e27746ea.png)
![A8FFD851-D35D-4318-9FA0-06B2818F9093](https://user-images.githubusercontent.com/51668635/77809636-d4710680-7090-11ea-8f41-e42fd9fd5ee5.png)

Only happend once which is weird. I'll update this if it happens again.

**Comment by gkeep** [comment]
I think it's because he changed a symbol like Latin 'a' to Cyrillic 'a' or a ' ' (space) to ' ' (Alt+255 - ASCII code).

Essentially, these names *appears* the same, but on a technical level they are not.

**Comment by wstyres** [comment]
Quite clever, we're going to be switching to email filtering (in #999) so that only one email has to be added instead of adding all of the different author variants. This is still susceptible to the same problem but I would assume that this would require a lot of different emails to be created. I'm not sure how Packix has that system set up but if he can change his name then he might also just be able to change his email...

**Comment by wstyres** [comment]
Packages are now filtered by an authors email instead of their name as of 33fd4fa00534065fedd4a99e27d70eea7b13a0ea.
